server:
  port: 8443
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true # 是否启用注册服务 默认为true, false是不启用
  instance:
      prefer-ip-address: true
spring:
  application:
    name: cmp-gateway
  cloud:
    gateway:
      routes:
        #      - id: route_service_one
        #        uri: http://localhost:8081
        #        predicates:
        #        - Path=/user/who
        - id: api-user
          uri: lb://cmp-user # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
          predicates:
            - Path=/userapi/**
          filters:
            - StripPrefix=1 # 表示在转发时去掉userapi