server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true # 是否启用注册服务 默认为true, false是不启用
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cmp-config
  cloud:
    config:
      server:
        git:
          username: 15321759239@163.com
          password: zxyazx1314
          searchPaths: respo
          uri: https://github.com/chizixin/myconfig/
      label: master



